# Scaleway configuration file
# https://github.com/scaleway/scaleway-sdk-go/tree/master/scw#scaleway-config

# This configuration file can be used with:
# - Scaleway SDK Go (https://github.com/scaleway/scaleway-sdk-go)
# - Scaleway CLI (>2.0.0) (https://github.com/scaleway/scaleway-cli)
# - Scaleway Terraform Provider (https://www.terraform.io/docs/providers/scaleway/index.html)

# You need an access key and a secret key to connect to Scaleway API.
# Generate your token at the following address: https://console.scaleway.com/iam/api-keys

# An access key is a secret key identifier.
access_key: SCWXXXXXXXXXXXXXXXXX

# The secret key is the value that can be used to authenticate against the API (the value used in X-Auth-Token HTTP-header).
# The secret key MUST remain secret and not given to anyone or published online.
secret_key: 01234567-abcd-effe-dcba-012345678910

# Your organization ID is the identifier of your account inside Scaleway infrastructure.
default_organization_id: 11111111-2222-3333-4444-555555555555

# Your project ID is the identifier of the project your resources are attached to (beta).
default_project_id: 11111111-2222-3333-4444-555555555555

# A region is represented as a geographical area such as France (Paris) or the Netherlands (Amsterdam).
# It can contain multiple availability zones.
# Example of region: fr-par, nl-ams
default_region: nl-ams

# A region can be split into many availability zones (AZ).
# Latency between multiple AZ of the same region are low as they have a common network layer.
# Example of zones: fr-par-1, nl-ams-1
default_zone: nl-ams-1

# APIURL overrides the API URL of the Scaleway API to the given URL.
# Change that if you want to direct requests to a different endpoint.
# api_url: https://api.scaleway.com

# Insecure enables insecure transport on the client.
# Default to false
# insecure: false

# A configuration is a named set of Scaleway properties.
# Starting off with a Scaleway SDK or Scaleway CLI, youâ€™ll work with a single configuration named default.
# You can set properties of the default profile by running either scw init or scw config set. 
# This single default configuration is suitable for most use cases.
# active_profile: myProfile

# To improve the Scaleway CLI we rely on diagnostic and usage data.
# Sending such data is optional and can be disable at any time by setting send_telemetry variable to false.
# send_telemetry: false

# To work with multiple projects or authorization accounts, you can set up multiple configurations with scw config configurations create and switch among them accordingly.
# You can use a profile by either:
# - Define the profile you want to use as the SCW_PROFILE environment variable
# - Use the GetActiveProfile() function in the SDK
# - Use the --profile flag with the CLI

# You can define a profile using the following syntax:

profiles:
  other:
    access_key: SCWYYYYYYYYYYYYYYYYY
    secret_key: 99999999-9999-9999-9999-999999999999
    default_organization_id: 99999999-9999-9999-9999-999999999999
    default_project_id: 99999999-9999-9999-9999-999999999999
    default_zone: fr-par-1
    default_region: fr-par
    api_url: https://api.scaleway.com
    insecure: false
    
  incomplete:
    access_key: SCW11111111111111111
    secret_key: 11111111-1111-1111-1111-111111111111
    # default_organization_id: 11111111-1111-1111-1111-111111111111
    # default_project_id: 11111111-1111-1111-1111-111111111111
    default_zone: pl-waw-1
    # default_region: fr-par
    # api_url: https://api.scaleway.com
    # insecure: false

