name: Lint

permissions:
  contents: read
  checks: write
  pull-requests: read

on:
  pull_request:
  merge_group:

jobs:
  terrafmt:
    name: terrafmt
    runs-on: ubuntu-latest
    steps:
      # Checkout should always be before setup-go to ensure caching is working
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run terrafmt on documentation
        run: go tool terrafmt fmt --verbose --check ./docs

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.40.0
        env:
          CLICOLOR: 1

  tfproviderlint:
    name: tfproviderlint
    runs-on: ubuntu-latest
    steps:
      # Checkout should always be before setup-go to ensure caching is working
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Install tfproviderlint
        run: go install github.com/bflad/tfproviderlint/cmd/tfproviderlint
      - name: Run tfproviderlint
        run: make tfproviderlint
      - name: Run tfproviderlintx
        run: make tfproviderlintx

  tfproviderdocs:
    name: tfproviderdocs
    runs-on: ubuntu-latest
    steps:
      # Checkout should always be before setup-go to ensure caching is working
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - uses: hashicorp/setup-terraform@v3
      - run: go install github.com/bflad/tfproviderdocs@latest
      - run: make tfproviderdocs

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color -ignore SC2086

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.5.0
          args: --timeout 5m
